export const initialShogiPieces = [
  // Player 1 (Bottom)
  { id: 1, name: "Lance", position: "A1", image: "/pieces/Kyosha.svg" },
  { id: 2, name: "Knight", position: "B1", image: "/pieces/Keima.svg" },
  { id: 3, name: "SilverGeneral", position: "C1", image: "/pieces/Ginsho.svg" },
  { id: 4, name: "GoldGeneral", position: "D1", image: "/pieces/Kinsho.svg" },
  { id: 5, name: "King", position: "E1", image: "/pieces/Osho.svg" },
  { id: 6, name: "GoldGeneral", position: "F1", image: "/pieces/Kinsho.svg" },
  { id: 7, name: "SilverGeneral", position: "G1", image: "/pieces/Ginsho.svg" },
  { id: 8, name: "Knight", position: "H1", image: "/pieces/Keima.svg" },
  { id: 9, name: "Lance", position: "I1", image: "/pieces/Kyosha.svg" },

  // Second Row (Player 1)
  { id: 10, name: "Bishop", position: "B2", image: "/pieces/Kakugyuo.svg" },
  { id: 11, name: "Rook", position: "H2", image: "/pieces/Hisha.svg" },

  // Third Row (Player 1)
  { id: 12, name: "Pawn", position: "A3", image: "/pieces/Fuhyo.svg" },
  { id: 13, name: "Pawn", position: "B3", image: "/pieces/Fuhyo.svg" },
  { id: 14, name: "Pawn", position: "C3", image: "/pieces/Fuhyo.svg" },
  { id: 15, name: "Pawn", position: "D3", image: "/pieces/Fuhyo.svg" },
  { id: 16, name: "Pawn", position: "E3", image: "/pieces/Fuhyo.svg" },
  { id: 17, name: "Pawn", position: "F3", image: "/pieces/Fuhyo.svg" },
  { id: 18, name: "Pawn", position: "G3", image: "/pieces/Fuhyo.svg" },
  { id: 19, name: "Pawn", position: "H3", image: "/pieces/Fuhyo.svg" },
  { id: 20, name: "Pawn", position: "I3", image: "/pieces/Fuhyo.svg" },

  // Player 2 (Top)
  {
    id: 21,
    name: "Lance",
    position: "A9",
    image: "/pieces/Kyosha.svg",
    playerTwo: true,
  },
  {
    id: 22,
    name: "Knight",
    position: "B9",
    image: "/pieces/Keima.svg",
    playerTwo: true,
  },
  {
    id: 23,
    name: "SilverGeneral",
    position: "C9",
    image: "/pieces/Ginsho.svg",
    playerTwo: true,
  },
  {
    id: 24,
    name: "GoldGeneral",
    position: "D9",
    image: "/pieces/Kinsho.svg",
    playerTwo: true,
  },
  {
    id: 25,
    name: "OpposingKing",
    position: "E9",
    image: "/pieces/Gyokusho.svg",
    playerTwo: true,
  },
  {
    id: 26,
    name: "GoldGeneral",
    position: "F9",
    image: "/pieces/Kinsho.svg",
    playerTwo: true,
  },
  {
    id: 27,
    name: "SilverGeneral",
    position: "G9",
    image: "/pieces/Ginsho.svg",
    playerTwo: true,
  },
  {
    id: 28,
    name: "Knight",
    position: "H9",
    image: "/pieces/Keima.svg",
    playerTwo: true,
  },
  {
    id: 29,
    name: "Lance",
    position: "I9",
    image: "/pieces/Kyosha.svg",
    playerTwo: true,
  },

  // Second Row (Player 2)
  {
    id: 30,
    name: "Bishop",
    position: "B8",
    image: "/pieces/Kakugyuo.svg",
    playerTwo: true,
  },
  {
    id: 31,
    name: "Rook",
    position: "H8",
    image: "/pieces/Hisha.svg",
    playerTwo: true,
  },

  // Third Row (Player 2)
  {
    id: 32,
    name: "Pawn",
    position: "A7",
    image: "/pieces/Fuhyo.svg",
    playerTwo: true,
  },
  {
    id: 33,
    name: "Pawn",
    position: "B7",
    image: "/pieces/Fuhyo.svg",
    playerTwo: true,
  },
  {
    id: 34,
    name: "Pawn",
    position: "C7",
    image: "/pieces/Fuhyo.svg",
    playerTwo: true,
  },
  {
    id: 35,
    name: "Pawn",
    position: "D7",
    image: "/pieces/Fuhyo.svg",
    playerTwo: true,
  },
  {
    id: 36,
    name: "Pawn",
    position: "E7",
    image: "/pieces/Fuhyo.svg",
    playerTwo: true,
  },
  {
    id: 37,
    name: "Pawn",
    position: "F7",
    image: "/pieces/Fuhyo.svg",
    playerTwo: true,
  },
  {
    id: 38,
    name: "Pawn",
    position: "G7",
    image: "/pieces/Fuhyo.svg",
    playerTwo: true,
  },
  {
    id: 39,
    name: "Pawn",
    position: "H7",
    image: "/pieces/Fuhyo.svg",
    playerTwo: true,
  },
  {
    id: 40,
    name: "Pawn",
    position: "I7",
    image: "/pieces/Fuhyo.svg",
    playerTwo: true,
  },
];

export const pieceInfo = {
  King: {
    englishName: "King",
    name: "Osho 王將",
    description: "A king can move one square in any direction.",
  },
  OpposingKing: {
    englishName: "Opposing King 玉將",
    name: "Gyokusho",
    description: "Same as a King.",
  },
  GoldGeneral: {
    englishName: "Gold General",
    name: "Kinsho 金将",
    description:
      "A gold general can move one square in any direction except diagonally back.",
  },
  SilverGeneral: {
    englishName: "Silver General",
    name: "Ginsho 銀将",
    description:
      "A silver general can move one square diagonally any direction or one space forward.",
  },
  Knight: {
    englishName: "Knight",
    name: "Keima 桂馬",
    description:
      "A knight can jump one square forward, plus one square diagonally forward. It is the only piece allowed to jump other pieces in its path.",
  },
  Lance: {
    englishName: "Lance",
    name: "Kyosha 香車",
    description:
      "A lance can move any number of free squares directly forward. It cannot move in any other direction.",
  },
  Bishop: {
    englishName: "Bishop",
    name: "Kakugyuo 角行",
    description:
      "A bishop can move any number of free squares in any diagonal direction.",
  },
  Rook: {
    englishName: "Rook",
    name: "Hisha 飛車",
    description:
      "A rook can move any number of free squares forward, backward, left or right.",
  },
  Pawn: {
    englishName: "Pawn",
    name: "Fuhyo 歩兵",
    description: "A pawn can only move one square forward.",
  },

  // Promoted Pieces
  PromotedPawn: {
    englishName: "Promoted Pawn",
    name: "Tokin と金",
    description:
      "Moves like a Gold General - one square in any direction except diagonally back.",
  },
  PromotedSilver: {
    englishName: "Promoted Silver",
    name: "Narigin 成銀",
    description:
      "Moves like a Gold General - one square in any direction except diagonally back.",
  },
  PromotedKnight: {
    englishName: "Promoted Knight",
    name: "Narikei 成桂",
    description:
      "Moves like a Gold General - one square in any direction except diagonally back.",
  },
  PromotedLance: {
    englishName: "Promoted Lance",
    name: "Narikyo 成香",
    description:
      "Moves like a Gold General - one square in any direction except diagonally back.",
  },
  PromotedBishop: {
    englishName: "Promoted Bishop",
    name: "Ryuma 龍馬",
    description:
      "Combines Bishop and King movements - can move diagonally any distance OR one square in any direction.",
  },
  PromotedRook: {
    englishName: "Promoted Rook",
    name: "Ryuo 龍王",
    description:
      "Combines Rook and King movements - can move orthogonally any distance OR one square in any direction.",
  },
};

export const promotionRules = {
  Pawn: {
    promotedName: "PromotedPawn",
    promotedImage: "/pieces/Tokin.svg",
    promotionZone: [
      "A7",
      "A8",
      "A9",
      "B7",
      "B8",
      "B9",
      "C7",
      "C8",
      "C9",
      "D7",
      "D8",
      "D9",
      "E7",
      "E8",
      "E9",
      "F7",
      "F8",
      "F9",
      "G7",
      "G8",
      "G9",
      "H7",
      "H8",
      "H9",
      "I7",
      "I8",
      "I9",
    ],
    playerTwoPromotionZone: [
      "A1",
      "A2",
      "A3",
      "B1",
      "B2",
      "B3",
      "C1",
      "C2",
      "C3",
      "D1",
      "D2",
      "D3",
      "E1",
      "E2",
      "E3",
      "F1",
      "F2",
      "F3",
      "G1",
      "G2",
      "G3",
      "H1",
      "H2",
      "H3",
      "I1",
      "I2",
      "I3",
    ],
    mandatoryPromotionZone: [
      "A9",
      "B9",
      "C9",
      "D9",
      "E9",
      "F9",
      "G9",
      "H9",
      "I9",
    ],
    playerTwoMandatoryPromotionZone: [
      "A1",
      "B1",
      "C1",
      "D1",
      "E1",
      "F1",
      "G1",
      "H1",
      "I1",
    ],
  },
  SilverGeneral: {
    promotedName: "PromotedSilver",
    promotedImage: "/pieces/Narigin.svg",
    promotionZone: [
      "A7",
      "A8",
      "A9",
      "B7",
      "B8",
      "B9",
      "C7",
      "C8",
      "C9",
      "D7",
      "D8",
      "D9",
      "E7",
      "E8",
      "E9",
      "F7",
      "F8",
      "F9",
      "G7",
      "G8",
      "G9",
      "H7",
      "H8",
      "H9",
      "I7",
      "I8",
      "I9",
    ],
    playerTwoPromotionZone: [
      "A1",
      "A2",
      "A3",
      "B1",
      "B2",
      "B3",
      "C1",
      "C2",
      "C3",
      "D1",
      "D2",
      "D3",
      "E1",
      "E2",
      "E3",
      "F1",
      "F2",
      "F3",
      "G1",
      "G2",
      "G3",
      "H1",
      "H2",
      "H3",
      "I1",
      "I2",
      "I3",
    ],
  },
  Knight: {
    promotedName: "PromotedKnight",
    promotedImage: "/pieces/Narikei.svg",
    promotionZone: [
      "A7",
      "A8",
      "A9",
      "B7",
      "B8",
      "B9",
      "C7",
      "C8",
      "C9",
      "D7",
      "D8",
      "D9",
      "E7",
      "E8",
      "E9",
      "F7",
      "F8",
      "F9",
      "G7",
      "G8",
      "G9",
      "H7",
      "H8",
      "H9",
      "I7",
      "I8",
      "I9",
    ],
    playerTwoPromotionZone: [
      "A1",
      "A2",
      "A3",
      "B1",
      "B2",
      "B3",
      "C1",
      "C2",
      "C3",
      "D1",
      "D2",
      "D3",
      "E1",
      "E2",
      "E3",
      "F1",
      "F2",
      "F3",
      "G1",
      "G2",
      "G3",
      "H1",
      "H2",
      "H3",
      "I1",
      "I2",
      "I3",
    ],
    mandatoryPromotionZone: [
      "A8",
      "A9",
      "B8",
      "B9",
      "C8",
      "C9",
      "D8",
      "D9",
      "E8",
      "E9",
      "F8",
      "F9",
      "G8",
      "G9",
      "H8",
      "H9",
      "I8",
      "I9",
    ],
    playerTwoMandatoryPromotionZone: [
      "A1",
      "A2",
      "B1",
      "B2",
      "C1",
      "C2",
      "D1",
      "D2",
      "E1",
      "E2",
      "F1",
      "F2",
      "G1",
      "G2",
      "H1",
      "H2",
      "I1",
      "I2",
    ],
  },
  Lance: {
    promotedName: "PromotedLance",
    promotedImage: "/pieces/Narikyo.svg",
    promotionZone: [
      "A7",
      "A8",
      "A9",
      "B7",
      "B8",
      "B9",
      "C7",
      "C8",
      "C9",
      "D7",
      "D8",
      "D9",
      "E7",
      "E8",
      "E9",
      "F7",
      "F8",
      "F9",
      "G7",
      "G8",
      "G9",
      "H7",
      "H8",
      "H9",
      "I7",
      "I8",
      "I9",
    ],
    playerTwoPromotionZone: [
      "A1",
      "A2",
      "A3",
      "B1",
      "B2",
      "B3",
      "C1",
      "C2",
      "C3",
      "D1",
      "D2",
      "D3",
      "E1",
      "E2",
      "E3",
      "F1",
      "F2",
      "F3",
      "G1",
      "G2",
      "G3",
      "H1",
      "H2",
      "H3",
      "I1",
      "I2",
      "I3",
    ],
    mandatoryPromotionZone: [
      "A9",
      "B9",
      "C9",
      "D9",
      "E9",
      "F9",
      "G9",
      "H9",
      "I9",
    ],
    playerTwoMandatoryPromotionZone: [
      "A1",
      "B1",
      "C1",
      "D1",
      "E1",
      "F1",
      "G1",
      "H1",
      "I1",
    ],
  },
  Bishop: {
    promotedName: "PromotedBishop",
    promotedImage: "/pieces/Ryuma.svg",
    promotionZone: [
      "A7",
      "A8",
      "A9",
      "B7",
      "B8",
      "B9",
      "C7",
      "C8",
      "C9",
      "D7",
      "D8",
      "D9",
      "E7",
      "E8",
      "E9",
      "F7",
      "F8",
      "F9",
      "G7",
      "G8",
      "G9",
      "H7",
      "H8",
      "H9",
      "I7",
      "I8",
      "I9",
    ],
    playerTwoPromotionZone: [
      "A1",
      "A2",
      "A3",
      "B1",
      "B2",
      "B3",
      "C1",
      "C2",
      "C3",
      "D1",
      "D2",
      "D3",
      "E1",
      "E2",
      "E3",
      "F1",
      "F2",
      "F3",
      "G1",
      "G2",
      "G3",
      "H1",
      "H2",
      "H3",
      "I1",
      "I2",
      "I3",
    ],
  },
  Rook: {
    promotedName: "PromotedRook",
    promotedImage: "/pieces/Ryuo.svg",
    promotionZone: [
      "A7",
      "A8",
      "A9",
      "B7",
      "B8",
      "B9",
      "C7",
      "C8",
      "C9",
      "D7",
      "D8",
      "D9",
      "E7",
      "E8",
      "E9",
      "F7",
      "F8",
      "F9",
      "G7",
      "G8",
      "G9",
      "H7",
      "H8",
      "H9",
      "I7",
      "I8",
      "I9",
    ],
    playerTwoPromotionZone: [
      "A1",
      "A2",
      "A3",
      "B1",
      "B2",
      "B3",
      "C1",
      "C2",
      "C3",
      "D1",
      "D2",
      "D3",
      "E1",
      "E2",
      "E3",
      "F1",
      "F2",
      "F3",
      "G1",
      "G2",
      "G3",
      "H1",
      "H2",
      "H3",
      "I1",
      "I2",
      "I3",
    ],
  },
};
